#!/usr/bin/env bash
# Stack management script — generate, start, and stop per-user Docker Compose stacks.
# Usage: ./deploy/stack.sh <username> <command> [options]
set -euo pipefail

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE="$DEPLOY_DIR/template/docker-compose.template.yml"
WG_SCRIPT_TEMPLATE="$DEPLOY_DIR/template/generate-wg0.sh.template"
USERS_DIR="$DEPLOY_DIR/users"

usage() {
  cat >&2 <<EOF
Usage: $(basename "$0") <username> <command> [options]

Commands:
  generate                      Render docker-compose.<username>.yml from template
  up [--all] [--with <profile>] Start the stack (profiles from conf, or overrides)
  down [<service>]              Stop entire stack, or a specific service
  token-grab                    Grab Garmin tokens through the WireGuard tunnel
                                (wireguard container must already be running)

Options for 'up':
  --all                         Enable all optional profiles regardless of conf
  --with <profile>              Enable an extra profile for this run only
                                (can be repeated: --with wireguard --with gpt-mcp)

Profiles: whoop  gpt-mcp  wireguard

WireGuard token-grab workflow:
  1. ./deploy/stack.sh <user> up --with wireguard   # start tunnel
  2. bash /opt/<user>/wireguard/generate-wg0.sh      # (first time only)
  3. ./deploy/stack.sh <user> token-grab             # auth through tunnel
  4. ./deploy/stack.sh <user> down wireguard         # stop tunnel — stack unaffected

Examples:
  ./deploy/stack.sh connor generate
  ./deploy/stack.sh connor up
  ./deploy/stack.sh physiology up --with wireguard
  ./deploy/stack.sh physiology up --all
  ./deploy/stack.sh connor down
  ./deploy/stack.sh physiology down wireguard
  ./deploy/stack.sh connor token-grab
EOF
  exit 1
}

# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------
if [ $# -lt 2 ]; then usage; fi

USERNAME="$1"
COMMAND="$2"
shift 2

# ---------------------------------------------------------------------------
# Load user conf
# ---------------------------------------------------------------------------
CONF="$USERS_DIR/$USERNAME.conf"
if [ ! -f "$CONF" ]; then
  echo "Error: no config found for user '$USERNAME' at $CONF" >&2
  exit 1
fi

ENABLE_WHOOP=false
ENABLE_GPT_MCP=false
ENABLE_WIREGUARD=false
# shellcheck source=/dev/null
source "$CONF"

COMPOSE_FILE="$DEPLOY_DIR/docker-compose.$USERNAME.yml"
ENV_FILE="$DEPLOY_DIR/.env"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
compose() {
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" "$@"
}

require_compose_file() {
  if [ ! -f "$COMPOSE_FILE" ]; then
    echo "Error: $COMPOSE_FILE not found — run './deploy/stack.sh $USERNAME generate' first" >&2
    exit 1
  fi
}

env_val() {
  # Extract a single value from the .env file: env_val KEY [default]
  local key="$1" default="${2:-}"
  grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- || echo "$default"
}

# ---------------------------------------------------------------------------
# generate
# ---------------------------------------------------------------------------
cmd_generate() {
  if [ ! -f "$TEMPLATE" ]; then
    echo "Error: template not found at $TEMPLATE" >&2
    exit 1
  fi

  echo "==> Generating $COMPOSE_FILE"

  python3 - "$TEMPLATE" "$COMPOSE_FILE" "$USERNAME" <<'PYEOF'
import sys

template_path, output_path, username = sys.argv[1], sys.argv[2], sys.argv[3]

with open(template_path) as f:
    content = f.read()

content = content.replace("{{USERNAME}}", username)

header = (
    f"# Generated by: ./deploy/stack.sh {username} generate\n"
    f"# Do not edit directly — re-run generate to update.\n"
    f"# Source template: deploy/template/docker-compose.template.yml\n\n"
)

with open(output_path, "w") as f:
    f.write(header + content)

print(f"    Written: {output_path}")
PYEOF

  # Install wireguard generate script if wireguard is enabled in conf
  if [ "$ENABLE_WIREGUARD" = "true" ]; then
    WG_DIR="/opt/$USERNAME/wireguard"
    WG_SCRIPT="$WG_DIR/generate-wg0.sh"
    mkdir -p "$WG_DIR"
    sed "s/{{USERNAME}}/$USERNAME/g" "$WG_SCRIPT_TEMPLATE" > "$WG_SCRIPT"
    chmod +x "$WG_SCRIPT"
    echo "==> WireGuard generate script installed: $WG_SCRIPT"
    echo "    Next: fill in deploy/.wireguard.$USERNAME.env then run: bash $WG_SCRIPT"
  fi

  echo "==> Done."
}

# ---------------------------------------------------------------------------
# up
# ---------------------------------------------------------------------------
cmd_up() {
  require_compose_file

  local all_profiles=false
  local extra_profiles=()

  while [ $# -gt 0 ]; do
    case "$1" in
      --all) all_profiles=true ;;
      --with) shift; extra_profiles+=("$1") ;;
      *) echo "Unknown option for 'up': $1" >&2; usage ;;
    esac
    shift
  done

  local profile_args=()
  if [ "$all_profiles" = "true" ]; then
    profile_args+=(--profile whoop --profile gpt-mcp --profile wireguard)
  else
    [ "$ENABLE_WHOOP"     = "true" ] && profile_args+=(--profile whoop)
    [ "$ENABLE_GPT_MCP"   = "true" ] && profile_args+=(--profile gpt-mcp)
    [ "$ENABLE_WIREGUARD" = "true" ] && profile_args+=(--profile wireguard)
    for p in "${extra_profiles[@]}"; do
      profile_args+=(--profile "$p")
    done
  fi

  echo "==> Starting $USERNAME stack${profile_args:+ (extra profiles: ${extra_profiles[*]:-})}"
  compose "${profile_args[@]}" up -d --build
}

# ---------------------------------------------------------------------------
# down
# ---------------------------------------------------------------------------
cmd_down() {
  require_compose_file

  if [ $# -eq 0 ]; then
    echo "==> Stopping $USERNAME stack"
    compose --profile whoop --profile gpt-mcp --profile wireguard down
  else
    local target="$1"
    echo "==> Stopping service '$target' in $USERNAME stack"
    compose --profile whoop --profile gpt-mcp --profile wireguard stop "$target"
    compose --profile whoop --profile gpt-mcp --profile wireguard rm -f "$target"
  fi
}

# ---------------------------------------------------------------------------
# token-grab
# ---------------------------------------------------------------------------
cmd_token_grab() {
  local wg_container="${USERNAME}-wireguard"

  if ! docker ps --format '{{.Names}}' | grep -q "^${wg_container}$"; then
    echo "Error: WireGuard container '$wg_container' is not running." >&2
    echo "Start it first: ./deploy/stack.sh $USERNAME up --with wireguard" >&2
    exit 1
  fi

  if [ ! -f "$ENV_FILE" ]; then
    echo "Error: env file not found at $ENV_FILE" >&2
    exit 1
  fi

  local influx_db;     influx_db="$(env_val INFLUX_DATABASE GarminStats)"
  local influx_pass;   influx_pass="$(env_val INFLUX_WRITER_PASSWORD)"

  # The token-grab container shares wireguard's network namespace, which uses
  # an external DNS (e.g. 8.8.8.8) rather than Docker's internal resolver.
  # --add-host is incompatible with --network container:X, so we pass the
  # influxdb container's IP directly as INFLUXDB_HOST instead of the hostname.
  local influxdb_ip
  influxdb_ip=$(docker inspect --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "${USERNAME}-influxdb" 2>/dev/null)
  if [ -z "$influxdb_ip" ]; then
    echo "Error: could not determine IP of ${USERNAME}-influxdb — is the stack running?" >&2
    exit 1
  fi

  echo "==> Running Garmin token grab through WireGuard tunnel ($wg_container)"
  echo "    InfluxDB: $influxdb_ip (${USERNAME}-influxdb)"
  echo "    Tokens will be written to /opt/$USERNAME/garminconnect-tokens"
  echo "    Stop this container once authentication succeeds (Ctrl+C or it exits)."
  echo ""

  # Run an ephemeral garmin-fetch-data container sharing the wireguard network
  # namespace. garmin-fetch-data in the main stack stays on the standard network
  # and is unaffected. Once this exits, tokens are in the shared volume and
  # the persistent container will pick them up on its next poll cycle.
  docker run --rm -it \
    --name "${USERNAME}-garmin-token-grab" \
    --network "container:${wg_container}" \
    -v "/opt/${USERNAME}/garminconnect-tokens:/home/appuser/.garminconnect" \
    -e INFLUXDB_HOST="${influxdb_ip}" \
    -e INFLUXDB_PORT=8086 \
    -e INFLUXDB_VERSION=1 \
    -e INFLUXDB_ENDPOINT_IS_HTTP=true \
    -e INFLUXDB_USERNAME=garmin_writer \
    -e INFLUXDB_PASSWORD="${influx_pass}" \
    -e INFLUXDB_DATABASE="${influx_db}" \
    -e GARMINCONNECT_IS_CN=False \
    -e TAG_MEASUREMENTS_WITH_USER_EMAIL=True \
    "garmin-fetch-data:${USERNAME}"

  echo ""
  echo "==> Token grab complete."
  echo "    You can now stop WireGuard: ./deploy/stack.sh $USERNAME down wireguard"
  echo "    garmin-fetch-data will continue with a direct connection."
}

# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------
case "$COMMAND" in
  generate)    cmd_generate    "$@" ;;
  up)          cmd_up          "$@" ;;
  down)        cmd_down        "$@" ;;
  token-grab)  cmd_token_grab  "$@" ;;
  *) echo "Unknown command: $COMMAND" >&2; usage ;;
esac
