{
 "title": "Garmin Training Metrics",
 "time": { "from": "now-42d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SportGroup",
    "query": "Running : running|trail_running|treadmill_running|ultra_run, Cycling : road_biking|gravel_cycling|mountain_biking|cyclocross|virtual_ride|indoor_cycling, Inline skating : inline_skating, Strength : strength_training, Indoor cardio : indoor_cardio"
   }
  ]
 },
 "panels": [
  {
   "title": "Max HR - 95th percentile",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "SELECT percentile(\"maxHR\", 95)\nFROM \"ActivitySummary\"\nWHERE $timeFilter AND \"activity_type_tag\" =~ /${SportGroup:raw}/"
    }
   ]
  },
  {
   "title": "Max HR Observed",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "SELECT max(\"maxHR\")\nFROM \"ActivitySummary\"\nWHERE $timeFilter AND \"activity_type_tag\" =~ /${SportGroup:raw}/"
    }
   ]
  },
  {
   "title": "HRmax Estimate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"HRmax_est\") FROM \"PhysiologyDaily\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "HRR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"HRR\") FROM \"PhysiologyDaily\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Resting HR - Static Comparison (28 days)",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"restingHeartRate\")\nFROM \"DailyStats\"\nWHERE $timeFilter"
    },
    {
     "query": "SELECT moving_average(mean(\"restingHeartRate\"), 28)\nFROM \"DailyStats\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "HR Zones %HRR",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "alias": "Zone 1",
     "query": "SELECT\n  last(\"Z1_Low\")  AS \"HR Low\",\n  last(\"Z1_High\") AS \"HR High1\"\nFROM \"PhysiologyDaily\"\nWHERE $timeFilter"
    },
    {
     "alias": "Zone 2",
     "query": "SELECT\n  last(\"Z2_Low\")  AS \"HR Low\",\n  last(\"Z2_High\") AS \"HR High1\"\nFROM \"PhysiologyDaily\"\nWHERE $timeFilter"
    },
    {
     "alias": "Zone 3",
     "query": "SELECT\n  last(\"Z3_Low\")  AS \"HR Low\",\n  last(\"Z3_High\") AS \"HR High1\"\nFROM \"PhysiologyDaily\"\nWHERE $timeFilter"
    },
    {
     "alias": "Zone 4",
     "query": "SELECT\n  last(\"Z4_Low\")  AS \"HR Low\",\n  last(\"Z4_High\") AS \"HR High1\"\nFROM \"PhysiologyDaily\"\nWHERE $timeFilter"
    },
    {
     "alias": "Zone 5",
     "query": "SELECT\n  last(\"Z5_Low\")  AS \"HR Low\",\n  last(\"Z5_High\") AS \"HR High1\"\nFROM \"PhysiologyDaily\"\nWHERE $timeFilter"
    }
   ]
  },
  {
   "title": "HRV Static",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"avgOvernightHrv\")\nFROM \"SleepSummary\"\nWHERE $timeFilter"
    }
   ]
  },
  {
   "title": "RHR 7d Median",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"RHR_7d_median\") FROM \"PhysiologyDaily\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Garmin VO2 Max (Cycling)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "SELECT last(\"VO2_max_value_cycling\")\nFROM \"VO2_Max\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "Current Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "SELECT last(\"restingHeartRate\") FROM \"DailyStats\" WHERE $timeFilter"
    },
    {
     "query": "SELECT last(\"avgOvernightHrv\") FROM \"SleepSummary\" WHERE $timeFilter"
    },
    {
     "query": "SELECT last(\"VO2_max_value\") FROM \"VO2_Max\" WHERE $timeFilter"
    },
    {
     "query": "SELECT max(\"maxHR\") FROM \"ActivitySummary\" WHERE $timeFilter AND \"activity_type_tag\" =~ /${SportGroup:raw}/"
    }
   ]
  },
  {
   "title": "Garmin VO2 Max ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"VO2_max_value\")\nFROM \"VO2_Max\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "Garmin VO2 Max (Cycling)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"VO2_max_value_cycling\")\nFROM \"VO2_Max\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "Garmin VO2 Max",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "SELECT last(\"VO2_max_value\")\nFROM \"VO2_Max\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "Resting HR Time Series",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "SELECT mean(\"restingHeartRate\")\nFROM \"DailyStats\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "HRV baseline (overnight)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 47 },
   "targets": [
    {
     "query": "SELECT mean(\"avgOvernightHrv\")\nFROM \"SleepSummary\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  }
 ]
}