{
 "title": "Garmin Training Metrics",
 "time": { "from": "now-45d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SportGroup",
    "query": "Running : running|trail_running|treadmill_running|ultra_run, Cycling : road_biking|gravel_cycling|mountain_biking|cyclocross|virtual_ride|indoor_cycling, Inline skating : inline_skating, Strength : strength_training, Indoor cardio : indoor_cardio"
   }
  ]
 },
 "panels": [
  {
   "title": "Max HR - 95th percentile",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "SELECT percentile(\"maxHR\", 95)\nFROM \"ActivitySummary\"\nWHERE $timeFilter AND \"activity_type_tag\" =~ /${SportGroup:raw}/"
    }
   ]
  },
  {
   "title": "Max HR Observed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "SELECT max(\"maxHR\")\nFROM \"ActivitySummary\"\nWHERE $timeFilter AND \"activity_type_tag\" =~ /${SportGroup:raw}/"
    }
   ]
  },
  {
   "title": "HRmax Estimate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"HRmax_est\") FROM \"PhysiologyDaily\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "HRR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"HRR\") FROM \"PhysiologyDaily\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "RHR 7d Median",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"RHR_7d_median\") FROM \"PhysiologyDaily\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "HRV Static",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"avgOvernightHrv\")\nFROM \"SleepSummary\"\nWHERE $timeFilter"
    }
   ]
  },
  {
   "title": "TSS Fatigue (ATL)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"ATL_7_TSS\")\nFROM \"TrainingLoadDaily\"\nWHERE $timeFilter\n  AND \"Database_Name\"='GarminStats'\n  AND \"Device\"='fenix 8 - 51mm, AMOLED'"
    }
   ]
  },
  {
   "title": "TSS Fitness (CTL)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"CTL_42_TSS\")\nFROM \"TrainingLoadDaily\"\nWHERE $timeFilter\n  AND \"Database_Name\"='GarminStats'\n  AND \"Device\"='fenix 8 - 51mm, AMOLED'"
    }
   ]
  },
  {
   "title": "TSS Form (TSB)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"TSB_TSS\")\nFROM \"TrainingLoadDaily\"\nWHERE $timeFilter\n  AND \"Database_Name\"='GarminStats'\n  AND \"Device\"='fenix 8 - 51mm, AMOLED'"
    }
   ]
  },
  {
   "title": "Trimp Fatigue (ATL)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"ATL_7_TRIMP\")\nFROM \"TrainingLoadDaily\"\nWHERE $timeFilter\n  AND \"Database_Name\"='GarminStats'\n  AND \"Device\"='fenix 8 - 51mm, AMOLED'"
    }
   ]
  },
  {
   "title": "TRIMP Fitness (CTL)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"CTL_42_TRIMP\")\nFROM \"TrainingLoadDaily\"\nWHERE $timeFilter\n  AND \"Database_Name\"='GarminStats'\n  AND \"Device\"='fenix 8 - 51mm, AMOLED'"
    }
   ]
  },
  {
   "title": "Trimp Form (TSB)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"TSB_TRIMP\")\nFROM \"TrainingLoadDaily\"\nWHERE $timeFilter\n  AND \"Database_Name\"='GarminStats'\n  AND \"Device\"='fenix 8 - 51mm, AMOLED'"
    }
   ]
  },
  {
   "title": "Most Recent 5min VO2 Max",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"best5m_vo2_last\")\nFROM \"PerformanceDaily\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "GAP Calculated VO2Max",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"VO2max_est_run\")\nFROM \"PerformanceDaily\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Garmin VO2 Max ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"VO2_max_value\")\nFROM \"VO2_Max\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "Garmin VO2 Max (Cycling)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"VO2_max_value_cycling\")\nFROM \"VO2_Max\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "Fitness Age Model Calculation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"FitnessAge_model\")\nFROM \"PerformanceDaily\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Resting HR - Static Comparison (28 days)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"restingHeartRate\")\nFROM \"DailyStats\"\nWHERE $timeFilter"
    },
    {
     "query": "SELECT moving_average(mean(\"restingHeartRate\"), 28)\nFROM \"DailyStats\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "VAM 20_best_42d_m_per_h",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"VAM20_best_42d_m_per_h\")\nFROM \"PerformanceDaily\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "VAM30_best_42d_m_per_h",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"VAM30_best_42d_m_per_h\")\nFROM \"PerformanceDaily\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "VAM Mountain Performance 42 Days",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "m/h" } },
   "targets": [
    {
     "query": "SELECT last(\"VAM20_best_42d_m_per_h\")\nFROM \"PerformanceDaily\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT last(\"VAM30_best_42d_m_per_h\")\nFROM \"PerformanceDaily\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT last(\"best20m_hr_median\")\nFROM \"DerivedActivity\"\nWHERE $timeFilter\nAND \"sport_tag\" =~ /running/\nGROUP BY time($__interval) fill(null)"
    },
    {
     "query": "SELECT last(\"CTL_42_TRIMP\")\nFROM \"TrainingLoadDaily\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "best20m_hr_median",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"best20m_hr_median\")\nFROM \"DerivedActivity\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "CTL_42_TRIMP",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"CTL_42_TRIMP\")\nFROM \"TrainingLoadDaily\"\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Performance Metrics Combined",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "SELECT last(\"CTL_42_TRIMP\") AS CTL, last(\"ATL_7_TRIMP\") AS ATL, last(\"TSB_TRIMP\") AS TSB\nFROM \"TrainingLoadDaily\"\nWHERE $timeFilter\n  AND \"Database_Name\"='GarminStats'\n  AND \"Device\"='fenix 8 - 51mm, AMOLED'"
    }
   ]
  },
  {
   "title": "Performance Metrics Combined",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "query": "SELECT last(\"CTL_42_TSS\") AS CTL, last(\"ATL_7_TSS\") AS ATL, last(\"TSB_TSS\") AS TSB\nFROM \"TrainingLoadDaily\"\nWHERE $timeFilter\n  AND \"Database_Name\"='GarminStats'\n  AND \"Device\"='fenix 8 - 51mm, AMOLED'"
    }
   ]
  },
  {
   "title": "Performance Metrics Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "SELECT \"CTL_42_TRIMP\",\"ATL_7_TRIMP\",\"TSB_TRIMP\"\nFROM \"TrainingLoadDaily\"\nWHERE $timeFilter\n  AND \"Database_Name\"='GarminStats'\n  AND \"Device\"='fenix 8 - 51mm, AMOLED'"
    }
   ]
  },
  {
   "title": "Performance Metrics Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "query": "SELECT \"CTL_42_TSS\",\"ATL_7_TSS\",\"TSB_TSS\"\nFROM \"TrainingLoadDaily\"\nWHERE $timeFilter\n  AND \"Database_Name\"='GarminStats'\n  AND \"Device\"='fenix 8 - 51mm, AMOLED'"
    }
   ]
  },
  {
   "title": "HR Zones %HRR",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "Zone 1",
     "query": "SELECT\n  last(\"Z1_Low\")  AS \"HR Low\",\n  last(\"Z1_High\") AS \"HR High1\"\nFROM \"PhysiologyDaily\"\nWHERE $timeFilter"
    },
    {
     "alias": "Zone 2",
     "query": "SELECT\n  last(\"Z2_Low\")  AS \"HR Low\",\n  last(\"Z2_High\") AS \"HR High1\"\nFROM \"PhysiologyDaily\"\nWHERE $timeFilter"
    },
    {
     "alias": "Zone 3",
     "query": "SELECT\n  last(\"Z3_Low\")  AS \"HR Low\",\n  last(\"Z3_High\") AS \"HR High1\"\nFROM \"PhysiologyDaily\"\nWHERE $timeFilter"
    },
    {
     "alias": "Zone 4",
     "query": "SELECT\n  last(\"Z4_Low\")  AS \"HR Low\",\n  last(\"Z4_High\") AS \"HR High1\"\nFROM \"PhysiologyDaily\"\nWHERE $timeFilter"
    },
    {
     "alias": "Zone 5",
     "query": "SELECT\n  last(\"Z5_Low\")  AS \"HR Low\",\n  last(\"Z5_High\") AS \"HR High1\"\nFROM \"PhysiologyDaily\"\nWHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Current Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 32 },
   "targets": [
    {
     "query": "SELECT last(\"restingHeartRate\") FROM \"DailyStats\" WHERE $timeFilter"
    },
    {
     "query": "SELECT last(\"avgOvernightHrv\") FROM \"SleepSummary\" WHERE $timeFilter"
    },
    {
     "query": "SELECT last(\"VO2_max_value\") FROM \"VO2_Max\" WHERE $timeFilter"
    },
    {
     "query": "SELECT max(\"maxHR\") FROM \"ActivitySummary\" WHERE $timeFilter AND \"activity_type_tag\" =~ /${SportGroup:raw}/"
    }
   ]
  },
  {
   "title": "Garmin VO2 Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "SELECT last(\"VO2_max_value\")\nFROM \"VO2_Max\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "Garmin VO2 Max (Cycling)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "SELECT last(\"VO2_max_value_cycling\")\nFROM \"VO2_Max\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "Resting HR Time Series",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "SELECT mean(\"restingHeartRate\")\nFROM \"DailyStats\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  },
  {
   "title": "HRV baseline (overnight)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "query": "SELECT mean(\"avgOvernightHrv\")\nFROM \"SleepSummary\"\nWHERE $timeFilter\nGROUP BY time(1d) fill(null)"
    }
   ]
  }
 ]
}